### ISSUE TITLE
Shortcut (SC) doesn't show shortcuts anymore

### ISSUE THREAD

**Issue by dna75** [alfredapp/shortcuts-workflow#11]
### Workflow version

2024.1

### Alfred version

5.5 [2257]

### macOS version

Sonoma 14.2.1 (23C71)

### Debugger output

```alfred_debugger
Code 1: /Users/dna/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/83AC2649-C8BB-4EAF-9F51-D05ABD019FC7: execution error: Error: Error: Object kan niet worden opgevraagd. (-1728)
```

### More details

I don't know if this is happening since the 14.2.1 update, but it suddenly stopped working.

**Comment by vitorgalvao** [comment]
That’s not enough detail to know what’s going on, unfortunately. It could be that you have a broken shortcut or something similar. It may be related to the macOS version (the Shortcuts team has been breaking it particularly badly as of late), but since you’re not on the latest version, I’m unable to test. If you’re able to figure out something else, e.g. by finding a faulty shortcut, reply back and I can take another look.

But please do change your system to English temporarily when grabbing the debugger output, so we have the exact error message to search for.

**Comment by dna75** [comment]
I updated MacOs to 14.4.1 but the issue still occurs.
The error I get when entering 'SC' is;
Code 1: /Users/dna/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/535D749B-B3AC-4E2C-A963-3388A9DD05A6: execution error: Error: Error: Can't get object. (-1728)

If you need more info, please let me know.

**Comment by vitorgalvao** [comment]
Open the Script Editor app on your Mac [and set the language to JavaScript](https://support.apple.com/en-gb/guide/script-editor/scpedt1079/mac). Then run:

```JavaScript
Application("Shortcuts Events").shortcuts()
```

What do you get?

**Comment by dna75** [comment]
This is the output;
[Application("Shortcuts Events").shortcuts.byName("Opdracht 2"), Application("Shortcuts Events").shortcuts.byName("Opdracht 1"), Application("Shortcuts Events").shortcuts.byName("Opdracht"), Application("Shortcuts Events").shortcuts.byName("Radio 2"), Application("Shortcuts Events").shortcuts.byName("AirPlay To All Sonos"), Application("Shortcuts Events").shortcuts.byName("Play On Sonos"), Application("Shortcuts Events").shortcuts.byName("Walkie-Talkie"), Application("Shortcuts Events").shortcuts.byName("Start timer"), Application("Shortcuts Events").shortcuts.byName("TODO"), Application("Shortcuts Events").shortcuts.byName("Reminder"), Application("Shortcuts Events").shortcuts.byName("Sky Radio"), Application("Shortcuts Events").shortcuts.byName("Facedown Silent"), Application("Shortcuts Events").shortcuts.byName("Verstuur bericht"), Application("Shortcuts Events").shortcuts.byName("Controleer beschikbaarheid"), Application("Shortcuts Events").shortcuts.byName("Wekker"), Application("Shortcuts Events").shortcuts.byName("Normaal"), Application("Shortcuts Events").shortcuts.byName("Bedtijd"), Application("Shortcuts Events").shortcuts.byName("Watch niet storen"), Application("Shortcuts Events").shortcuts.byName("Bureau aan"), Application("Shortcuts Events").shortcuts.byName("Bureau uit"), Application("Shortcuts Events").shortcuts.byName("Maak pdf aan 4"), Application("Shortcuts Events").shortcuts.byName("Calm Notifications"), Application("Shortcuts Events").shortcuts.byName("Hallo"), Application("Shortcuts Events").shortcuts.byName("vogeltje"), Application("Shortcuts Events").shortcuts.byName("Stop"), Application("Shortcuts Events").shortcuts.byName("En nu naar?"), Application("Shortcuts Events").shortcuts.byName("Tv kijken"), Application("Shortcuts Events").shortcuts.byName("Ok Google"), Application("Shortcuts Events").shortcuts.byName("Tv uit"), Application("Shortcuts Events").shortcuts.byName("Shazam-opdracht"), Application("Shortcuts Events").shortcuts.byName("Super zuinig"), Application("Shortcuts Events").shortcuts.byName("Muziek"), Application("Shortcuts Events").shortcuts.byName("Opdracht 2"), Application("Shortcuts Events").shortcuts.byName("Lampen Aan 1"), Application("Shortcuts Events").shortcuts.byName("Radio 4"), Application("Shortcuts Events").shortcuts.byName("Sonos Zachter"), Application("Shortcuts Events").shortcuts.byName("Bruut"), Application("Shortcuts Events").shortcuts.byName("Sonos harder"), Application("Shortcuts Events").shortcuts.byName("Radio 3"), Application("Shortcuts Events").shortcuts.byName("Studio Ibiza"), Application("Shortcuts Events").shortcuts.byName("Studio Brussel"), Application("Shortcuts Events").shortcuts.byName("Sonos stop"), Application("Shortcuts Events").shortcuts.byName("Create PDF"), Application("Shortcuts Events").shortcuts.byName("Create PNG"), Application("Shortcuts Events").shortcuts.byName("Create JPG"), Application("Shortcuts Events").shortcuts.byName("Twee"), Application("Shortcuts Events").shortcuts.byName("België"), Application("Shortcuts Events").shortcuts.byName("Vuur"), Application("Shortcuts Events").shortcuts.byName("Ringtone 0%"), Application("Shortcuts Events").shortcuts.byName("Ringtone 30%"), Application("Shortcuts Events").shortcuts.byName("Current Time is within a time range"), Application("Shortcuts Events").shortcuts.byName("Tijd tussen…"), Application("Shortcuts Events").shortcuts.byName("Lampen aan"), Application("Shortcuts Events").shortcuts.byName("Lampen uit"), Application("Shortcuts Events").shortcuts.byName("Zolder uit"), Application("Shortcuts Events").shortcuts.byName("Lekker slapen"), Application("Shortcuts Events").shortcuts.byName("Zolder aan"), Application("Shortcuts Events").shortcuts.byName("Ibiza Global Radio"), Application("Shortcuts Events").shortcuts.byName("Film kijken"), Application("Shortcuts Events").shortcuts.byName("Roze")]

**Comment by vitorgalvao** [comment]
Now do:

```javascript
const allShortcuts = Application("Shortcuts Events").shortcuts()

const sfItems = allShortcuts.map(shortcut => {
  const name = shortcut.name()
  const folder = shortcut.folder.exists() ? shortcut.folder.name() : ""

  console.log("name: " + name)
  console.log("folder: " + folder)

  return { name: name, folder: folder }
})

sfItems
```

**Comment by dna75** [comment]
I don't get any errors, this is the output;

app = Application("Shortcuts Events")
	app.shortcuts()
		--> [app.shortcuts.byName("Radio 2"), app.shortcuts.byName("AirPlay To All Sonos"), app.shortcuts.byName("Play On Sonos"), app.shortcuts.byName("Walkie-Talkie"), app.shortcuts.byName("Start timer"), app.shortcuts.byName("TODO"), app.shortcuts.byName("Reminder"), app.shortcuts.byName("Sky Radio"), app.shortcuts.byName("Facedown Silent"), app.shortcuts.byName("Verstuur bericht"), app.shortcuts.byName("Controleer beschikbaarheid"), app.shortcuts.byName("Wekker"), app.shortcuts.byName("Normaal"), app.shortcuts.byName("Bedtijd"), app.shortcuts.byName("Watch niet storen"), app.shortcuts.byName("Bureau aan"), app.shortcuts.byName("Bureau uit"), app.shortcuts.byName("Maak pdf aan 4"), app.shortcuts.byName("Calm Notifications"), app.shortcuts.byName("Hallo"), app.shortcuts.byName("vogeltje"), app.shortcuts.byName("Stop"), app.shortcuts.byName("En nu naar?"), app.shortcuts.byName("Tv kijken"), app.shortcuts.byName("Ok Google"), app.shortcuts.byName("Tv uit"), app.shortcuts.byName("Shazam-opdracht"), app.shortcuts.byName("Super zuinig"), app.shortcuts.byName("Muziek"), app.shortcuts.byName("Opdracht 2"), app.shortcuts.byName("Lampen Aan 1"), app.shortcuts.byName("Radio 4"), app.shortcuts.byName("Sonos Zachter"), app.shortcuts.byName("Bruut"), app.shortcuts.byName("Sonos harder"), app.shortcuts.byName("Radio 3"), app.shortcuts.byName("Studio Ibiza"), app.shortcuts.byName("Studio Brussel"), app.shortcuts.byName("Sonos stop"), app.shortcuts.byName("Create PDF"), app.shortcuts.byName("Create PNG"), app.shortcuts.byName("Create JPG"), app.shortcuts.byName("Twee"), app.shortcuts.byName("België"), app.shortcuts.byName("Vuur"), app.shortcuts.byName("Ringtone 0%"), app.shortcuts.byName("Ringtone 30%"), app.shortcuts.byName("Current Time is within a time range"), app.shortcuts.byName("Tijd tussen…"), app.shortcuts.byName("Lampen aan"), app.shortcuts.byName("Lampen uit"), app.shortcuts.byName("Zolder uit"), app.shortcuts.byName("Lekker slapen"), app.shortcuts.byName("Zolder aan"), app.shortcuts.byName("Ibiza Global Radio"), app.shortcuts.byName("Film kijken"), app.shortcuts.byName("Roze")]
	app.shortcuts.byName("Radio 2").name()
		--> "Radio 2"
	app.exists(app.shortcuts.byName("Radio 2").folder)
		--> false

/* name: Radio 2 */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("AirPlay To All Sonos").name()
		--> "AirPlay To All Sonos"
	app.exists(app.shortcuts.byName("AirPlay To All Sonos").folder)
		--> false

/* name: AirPlay To All Sonos */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Play On Sonos").name()
		--> "Play On Sonos"
	app.exists(app.shortcuts.byName("Play On Sonos").folder)
		--> false

/* name: Play On Sonos */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Walkie-Talkie").name()
		--> "Walkie-Talkie"
	app.exists(app.shortcuts.byName("Walkie-Talkie").folder)
		--> false

/* name: Walkie-Talkie */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Start timer").name()
		--> "Start timer"
	app.exists(app.shortcuts.byName("Start timer").folder)
		--> false

/* name: Start timer */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("TODO").name()
		--> "TODO"
	app.exists(app.shortcuts.byName("TODO").folder)
		--> false

/* name: TODO */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Reminder").name()
		--> "Reminder"
	app.exists(app.shortcuts.byName("Reminder").folder)
		--> false

/* name: Reminder */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Sky Radio").name()
		--> "Sky Radio"
	app.exists(app.shortcuts.byName("Sky Radio").folder)
		--> false

/* name: Sky Radio */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Facedown Silent").name()
		--> "Facedown Silent"
	app.exists(app.shortcuts.byName("Facedown Silent").folder)
		--> false

/* name: Facedown Silent */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Verstuur bericht").name()
		--> "Verstuur bericht"
	app.exists(app.shortcuts.byName("Verstuur bericht").folder)
		--> false

/* name: Verstuur bericht */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Controleer beschikbaarheid").name()
		--> "Controleer beschikbaarheid"
	app.exists(app.shortcuts.byName("Controleer beschikbaarheid").folder)
		--> false

/* name: Controleer beschikbaarheid */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Wekker").name()
		--> "Wekker"
	app.exists(app.shortcuts.byName("Wekker").folder)
		--> false

/* name: Wekker */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Normaal").name()
		--> "Normaal"
	app.exists(app.shortcuts.byName("Normaal").folder)
		--> false

/* name: Normaal */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Bedtijd").name()
		--> "Bedtijd"
	app.exists(app.shortcuts.byName("Bedtijd").folder)
		--> false

/* name: Bedtijd */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Watch niet storen").name()
		--> "Watch niet storen"
	app.exists(app.shortcuts.byName("Watch niet storen").folder)
		--> false

/* name: Watch niet storen */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Bureau aan").name()
		--> "Bureau aan"
	app.exists(app.shortcuts.byName("Bureau aan").folder)
		--> false

/* name: Bureau aan */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Bureau uit").name()
		--> "Bureau uit"
	app.exists(app.shortcuts.byName("Bureau uit").folder)
		--> false

/* name: Bureau uit */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Maak pdf aan 4").name()
		--> "Maak pdf aan 4"
	app.exists(app.shortcuts.byName("Maak pdf aan 4").folder)
		--> false

/* name: Maak pdf aan 4 */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Calm Notifications").name()
		--> "Calm Notifications"
	app.exists(app.shortcuts.byName("Calm Notifications").folder)
		--> false

/* name: Calm Notifications */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Hallo").name()
		--> "Hallo"
	app.exists(app.shortcuts.byName("Hallo").folder)
		--> false

/* name: Hallo */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("vogeltje").name()
		--> "vogeltje"
	app.exists(app.shortcuts.byName("vogeltje").folder)
		--> false

/* name: vogeltje */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Stop").name()
		--> "Stop"
	app.exists(app.shortcuts.byName("Stop").folder)
		--> false

/* name: Stop */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("En nu naar?").name()
		--> "En nu naar?"
	app.exists(app.shortcuts.byName("En nu naar?").folder)
		--> false

/* name: En nu naar? */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Tv kijken").name()
		--> "Tv kijken"
	app.exists(app.shortcuts.byName("Tv kijken").folder)
		--> false

/* name: Tv kijken */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Ok Google").name()
		--> "Ok Google"
	app.exists(app.shortcuts.byName("Ok Google").folder)
		--> false

/* name: Ok Google */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Tv uit").name()
		--> "Tv uit"
	app.exists(app.shortcuts.byName("Tv uit").folder)
		--> false

/* name: Tv uit */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Shazam-opdracht").name()
		--> "Shazam-opdracht"
	app.exists(app.shortcuts.byName("Shazam-opdracht").folder)
		--> false

/* name: Shazam-opdracht */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Super zuinig").name()
		--> "Super zuinig"
	app.exists(app.shortcuts.byName("Super zuinig").folder)
		--> false

/* name: Super zuinig */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Muziek").name()
		--> "Muziek"
	app.exists(app.shortcuts.byName("Muziek").folder)
		--> false

/* name: Muziek */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Opdracht 2").name()
		--> "Opdracht 2"
	app.exists(app.shortcuts.byName("Opdracht 2").folder)
		--> false

/* name: Opdracht 2 */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Lampen Aan 1").name()
		--> "Lampen Aan 1"
	app.exists(app.shortcuts.byName("Lampen Aan 1").folder)
		--> false

/* name: Lampen Aan 1 */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Radio 4").name()
		--> "Radio 4"
	app.exists(app.shortcuts.byName("Radio 4").folder)
		--> false

/* name: Radio 4 */
/* folder:  */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Sonos Zachter").name()
		--> "Sonos Zachter"
	app.exists(app.shortcuts.byName("Sonos Zachter").folder)
		--> true
	app.shortcuts.byName("Sonos Zachter").folder.name()
		--> "Muziek"

/* name: Sonos Zachter */
/* folder: Muziek */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Bruut").name()
		--> "Bruut"
	app.exists(app.shortcuts.byName("Bruut").folder)
		--> true
	app.shortcuts.byName("Bruut").folder.name()
		--> "Muziek"

/* name: Bruut */
/* folder: Muziek */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Sonos harder").name()
		--> "Sonos harder"
	app.exists(app.shortcuts.byName("Sonos harder").folder)
		--> true
	app.shortcuts.byName("Sonos harder").folder.name()
		--> "Muziek"

/* name: Sonos harder */
/* folder: Muziek */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Radio 3").name()
		--> "Radio 3"
	app.exists(app.shortcuts.byName("Radio 3").folder)
		--> true
	app.shortcuts.byName("Radio 3").folder.name()
		--> "Muziek"

/* name: Radio 3 */
/* folder: Muziek */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Studio Ibiza").name()
		--> "Studio Ibiza"
	app.exists(app.shortcuts.byName("Studio Ibiza").folder)
		--> true
	app.shortcuts.byName("Studio Ibiza").folder.name()
		--> "Muziek"

/* name: Studio Ibiza */
/* folder: Muziek */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Studio Brussel").name()
		--> "Studio Brussel"
	app.exists(app.shortcuts.byName("Studio Brussel").folder)
		--> true
	app.shortcuts.byName("Studio Brussel").folder.name()
		--> "Muziek"

/* name: Studio Brussel */
/* folder: Muziek */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Sonos stop").name()
		--> "Sonos stop"
	app.exists(app.shortcuts.byName("Sonos stop").folder)
		--> true
	app.shortcuts.byName("Sonos stop").folder.name()
		--> "Muziek"

/* name: Sonos stop */
/* folder: Muziek */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Create PDF").name()
		--> "Create PDF"
	app.exists(app.shortcuts.byName("Create PDF").folder)
		--> true
	app.shortcuts.byName("Create PDF").folder.name()
		--> "MacOS quick tasks"

/* name: Create PDF */
/* folder: MacOS quick tasks */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Create PNG").name()
		--> "Create PNG"
	app.exists(app.shortcuts.byName("Create PNG").folder)
		--> true
	app.shortcuts.byName("Create PNG").folder.name()
		--> "MacOS quick tasks"

/* name: Create PNG */
/* folder: MacOS quick tasks */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Create JPG").name()
		--> "Create JPG"
	app.exists(app.shortcuts.byName("Create JPG").folder)
		--> true
	app.shortcuts.byName("Create JPG").folder.name()
		--> "MacOS quick tasks"

/* name: Create JPG */
/* folder: MacOS quick tasks */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Twee").name()
		--> "Twee"
	app.exists(app.shortcuts.byName("Twee").folder)
		--> true
	app.shortcuts.byName("Twee").folder.name()
		--> "Auto"

/* name: Twee */
/* folder: Auto */
app = Application("Shortcuts Events")
	app.shortcuts.byName("België").name()
		--> "België"
	app.exists(app.shortcuts.byName("België").folder)
		--> true
	app.shortcuts.byName("België").folder.name()
		--> "Auto"

/* name: België */
/* folder: Auto */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Vuur").name()
		--> "Vuur"
	app.exists(app.shortcuts.byName("Vuur").folder)
		--> true
	app.shortcuts.byName("Vuur").folder.name()
		--> "Auto"

/* name: Vuur */
/* folder: Auto */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Ringtone 0%").name()
		--> "Ringtone 0%"
	app.exists(app.shortcuts.byName("Ringtone 0%").folder)
		--> true
	app.shortcuts.byName("Ringtone 0%").folder.name()
		--> "Ringtone aanpassen"

/* name: Ringtone 0% */
/* folder: Ringtone aanpassen */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Ringtone 30%").name()
		--> "Ringtone 30%"
	app.exists(app.shortcuts.byName("Ringtone 30%").folder)
		--> true
	app.shortcuts.byName("Ringtone 30%").folder.name()
		--> "Ringtone aanpassen"

/* name: Ringtone 30% */
/* folder: Ringtone aanpassen */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Current Time is within a time range").name()
		--> "Current Time is within a time range"
	app.exists(app.shortcuts.byName("Current Time is within a time range").folder)
		--> true
	app.shortcuts.byName("Current Time is within a time range").folder.name()
		--> "Automatisering"

/* name: Current Time is within a time range */
/* folder: Automatisering */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Tijd tussen…").name()
		--> "Tijd tussen…"
	app.exists(app.shortcuts.byName("Tijd tussen…").folder)
		--> true
	app.shortcuts.byName("Tijd tussen…").folder.name()
		--> "Automatisering"

/* name: Tijd tussen… */
/* folder: Automatisering */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Lampen aan").name()
		--> "Lampen aan"
	app.exists(app.shortcuts.byName("Lampen aan").folder)
		--> true
	app.shortcuts.byName("Lampen aan").folder.name()
		--> "Verlichting"

/* name: Lampen aan */
/* folder: Verlichting */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Lampen uit").name()
		--> "Lampen uit"
	app.exists(app.shortcuts.byName("Lampen uit").folder)
		--> true
	app.shortcuts.byName("Lampen uit").folder.name()
		--> "Verlichting"

/* name: Lampen uit */
/* folder: Verlichting */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Zolder uit").name()
		--> "Zolder uit"
	app.exists(app.shortcuts.byName("Zolder uit").folder)
		--> true
	app.shortcuts.byName("Zolder uit").folder.name()
		--> "Verlichting"

/* name: Zolder uit */
/* folder: Verlichting */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Lekker slapen").name()
		--> "Lekker slapen"
	app.exists(app.shortcuts.byName("Lekker slapen").folder)
		--> true
	app.shortcuts.byName("Lekker slapen").folder.name()
		--> "Verlichting"

/* name: Lekker slapen */
/* folder: Verlichting */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Zolder aan").name()
		--> "Zolder aan"
	app.exists(app.shortcuts.byName("Zolder aan").folder)
		--> true
	app.shortcuts.byName("Zolder aan").folder.name()
		--> "Verlichting"

/* name: Zolder aan */
/* folder: Verlichting */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Ibiza Global Radio").name()
		--> "Ibiza Global Radio"
	app.exists(app.shortcuts.byName("Ibiza Global Radio").folder)
		--> true
	app.shortcuts.byName("Ibiza Global Radio").folder.name()
		--> "Verlichting"

/* name: Ibiza Global Radio */
/* folder: Verlichting */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Film kijken").name()
		--> "Film kijken"
	app.exists(app.shortcuts.byName("Film kijken").folder)
		--> true
	app.shortcuts.byName("Film kijken").folder.name()
		--> "Verlichting"

/* name: Film kijken */
/* folder: Verlichting */
app = Application("Shortcuts Events")
	app.shortcuts.byName("Roze").name()
		--> "Roze"
	app.exists(app.shortcuts.byName("Roze").folder)
		--> true
	app.shortcuts.byName("Roze").folder.name()
		--> "Verlichting"

/* name: Roze */
/* folder: Verlichting */
Resultaat:
[{"name":"Radio 2", "folder":""}, {"name":"AirPlay To All Sonos", "folder":""}, {"name":"Play On Sonos", "folder":""}, {"name":"Walkie-Talkie", "folder":""}, {"name":"Start timer", "folder":""}, {"name":"TODO", "folder":""}, {"name":"Reminder", "folder":""}, {"name":"Sky Radio", "folder":""}, {"name":"Facedown Silent", "folder":""}, {"name":"Verstuur bericht", "folder":""}, {"name":"Controleer beschikbaarheid", "folder":""}, {"name":"Wekker", "folder":""}, {"name":"Normaal", "folder":""}, {"name":"Bedtijd", "folder":""}, {"name":"Watch niet storen", "folder":""}, {"name":"Bureau aan", "folder":""}, {"name":"Bureau uit", "folder":""}, {"name":"Maak pdf aan 4", "folder":""}, {"name":"Calm Notifications", "folder":""}, {"name":"Hallo", "folder":""}, {"name":"vogeltje", "folder":""}, {"name":"Stop", "folder":""}, {"name":"En nu naar?", "folder":""}, {"name":"Tv kijken", "folder":""}, {"name":"Ok Google", "folder":""}, {"name":"Tv uit", "folder":""}, {"name":"Shazam-opdracht", "folder":""}, {"name":"Super zuinig", "folder":""}, {"name":"Muziek", "folder":""}, {"name":"Opdracht 2", "folder":""}, {"name":"Lampen Aan 1", "folder":""}, {"name":"Radio 4", "folder":""}, {"name":"Sonos Zachter", "folder":"Muziek"}, {"name":"Bruut", "folder":"Muziek"}, {"name":"Sonos harder", "folder":"Muziek"}, {"name":"Radio 3", "folder":"Muziek"}, {"name":"Studio Ibiza", "folder":"Muziek"}, {"name":"Studio Brussel", "folder":"Muziek"}, {"name":"Sonos stop", "folder":"Muziek"}, {"name":"Create PDF", "folder":"MacOS quick tasks"}, {"name":"Create PNG", "folder":"MacOS quick tasks"}, {"name":"Create JPG", "folder":"MacOS quick tasks"}, {"name":"Twee", "folder":"Auto"}, {"name":"België", "folder":"Auto"}, {"name":"Vuur", "folder":"Auto"}, {"name":"Ringtone 0%", "folder":"Ringtone aanpassen"}, {"name":"Ringtone 30%", "folder":"Ringtone aanpassen"}, {"name":"Current Time is within a time range", "folder":"Automatisering"}, {"name":"Tijd tussen…", "folder":"Automatisering"}, {"name":"Lampen aan", "folder":"Verlichting"}, {"name":"Lampen uit", "folder":"Verlichting"}, {"name":"Zolder uit", "folder":"Verlichting"}, {"name":"Lekker slapen", "folder":"Verlichting"}, {"name":"Zolder aan", "folder":"Verlichting"}, {"name":"Ibiza Global Radio", "folder":"Verlichting"}, {"name":"Film kijken", "folder":"Verlichting"}, {"name":"Roze", "folder":"Verlichting"}]

**Comment by dna75** [comment]
I have no clue what happend but after my last comment I tried the SC command in Alfred again and now it's working without any issues.
