### ISSUE TITLE
Run a shortcut directly without having to type "sc" first?

### ISSUE THREAD

**Issue by zizhengwu** [alfredapp/shortcuts-workflow#6]
For example, in the following image, can I type "Add to a Playlist" in Alfred to run this shortcut directly?

![image](https://user-images.githubusercontent.com/2246655/217145089-aa13f46d-8f0d-443b-b2e1-82b0121ca334.png)

**Comment by vitorgalvao** [comment]
Not with this Workflow, whose goal is to show you the list, but you can easily make that yourself by connecting a [Keyword Input](https://www.alfredapp.com/help/workflows/inputs/keyword/) to a [Run Shortcut](https://www.alfredapp.com/help/workflows/automations/run-shortcut/).
