### ISSUE TITLE
Hotkey

### ISSUE THREAD

**Issue by notDavid** [alfredapp/shortcuts-workflow#7]
### Feature details

Hi there,

please consider adding a "Hotkey" to the workflow.
(i can add it myself, but the updates will overwrite this of course...)

Thank you!

**Comment by vitorgalvao** [comment]
I have now added this locally. A Single Hotkey to show the main `sc` view. I have another change staged which will be released after the new year so this will be out at the same time. I recommend you set your own Hotkey for now and then you can switch the one in the workflow once the new version is out.
