### ISSUE TITLE
New shortcuts don't show up in the list

### ISSUE THREAD

**Issue by sohate** [alfredapp/shortcuts-workflow#8]
### Workflow version

v2023.8

### Alfred version

5.1.4 [2196]

### macOS version

13.6.3

### Debugger output

```alfred_debugger
Comment is too long
```

### More details

Can't execute new shortcuts because workflow doesn't see them.

**Comment by vitorgalvao** [comment]
Please fill the debugger output. It’s impossible to help without that.

**Comment by sohate** [comment]
@vitorgalvao here
[debug.txt](https://github.com/alfredapp/shortcuts-workflow/files/13803620/debug.txt)

**Comment by vitorgalvao** [comment]
From the instructions:

> The list of shortcuts is cached for faster results. An immediate cache rebuild can be forced with <kbd>⌘</kbd><kbd>⌥</kbd><kbd>⌃</kbd><kbd>↩︎</kbd>.
